export const peliculas = [
  {
    id: '1',
    name: "No Respires II",
    img: require("../assets/norespires.jpg"),
    price: 255,
    language: 'Español',
    horario: '1:30 PM, 3:45 PM',
    genero: 'Terror',
    duracion: '2h 2min',
    trailer: 'watch?v=41kMPKpZ_ps',
    star: 3,
    synopsis: 'El ex militar ciego que causó estragos en la primera entrega, volverá a verse envuelto en problemas. En aquella ocasión el hombre consiguió acabar de manera violenta con algunos de los jóvenes que tratan de entrar a robar a su hogar. Ahora, parece que un grupo de amigos ha entrado en su casa, pero con intenciones bien diferentes: van a tratar de tomarse venganza por sus malogrados colegas, en el asalto tiempo atrás.',
  },

  {
    id: '2',
    name: "Un Lugar en Silencio",
    img: require("../assets/lugarsilencio.jpg"),
    price: 249,
    language: 'Ingles',
    horario: '1:30 PM, 3:45 PM',
    genero: 'Terror',
    duracion: '1h 25min',
    trailer: 'watch?v=41kMPKpZ_ps',
    star: 3,
    synopsis: 'El ex militar ciego que causó estragos en la primera entrega, volverá a verse envuelto en problemas. En aquella ocasión el hombre consiguió acabar de manera violenta con algunos de los jóvenes que tratan de entrar a robar a su hogar. Ahora, parece que un grupo de amigos ha entrado en su casa, pero con intenciones bien diferentes: van a tratar de tomarse venganza por sus malogrados colegas, en el asalto tiempo atrás.',
  },
  {
    id: '3',
    name: "El Bosque Maldito",
    img: require("../assets/bosquemaldito.jpg"),
    price: 279,
    language: 'Español',
    horario: '1:30 PM, 3:45 PM',
    genero: 'Terror',
    duracion: '1h 52min',
    trailer: 'watch?v=41kMPKpZ_ps',
    star: 3,
    synopsis: 'El ex militar ciego que causó estragos en la primera entrega, volverá a verse envuelto en problemas. En aquella ocasión el hombre consiguió acabar de manera violenta con algunos de los jóvenes que tratan de entrar a robar a su hogar. Ahora, parece que un grupo de amigos ha entrado en su casa, pero con intenciones bien diferentes: van a tratar de tomarse venganza por sus malogrados colegas, en el asalto tiempo atrás.',
  },
  {
    id: '4',
    name: "The Prodigy",
    img: require("../assets/prodigy.jpg"),
    price: 289,
    language: 'Ingles',
    horario: '1:30 PM, 3:45 PM',
    genero: 'Terror',
    duracion: '1h 48min',
    trailer: 'watch?v=41kMPKpZ_ps',
    star: 3,
    synopsis: 'El ex militar ciego que causó estragos en la primera entrega, volverá a verse envuelto en problemas. En aquella ocasión el hombre consiguió acabar de manera violenta con algunos de los jóvenes que tratan de entrar a robar a su hogar. Ahora, parece que un grupo de amigos ha entrado en su casa, pero con intenciones bien diferentes: van a tratar de tomarse venganza por sus malogrados colegas, en el asalto tiempo atrás.',
  },
  {
    id: '5',
    name: "The Conjuring 3",
    img: require("../assets/conjuring.jpg"),
    price: 279,
    language: 'Español',
    horario: '1:30 PM, 3:45 PM',
    genero: 'Terror',
    duracion: '2h 12min',
    trailer: 'watch?v=41kMPKpZ_ps',
    star: 3,
    synopsis: 'El ex militar ciego que causó estragos en la primera entrega, volverá a verse envuelto en problemas. En aquella ocasión el hombre consiguió acabar de manera violenta con algunos de los jóvenes que tratan de entrar a robar a su hogar. Ahora, parece que un grupo de amigos ha entrado en su casa, pero con intenciones bien diferentes: van a tratar de tomarse venganza por sus malogrados colegas, en el asalto tiempo atrás.',
  },
  {
    id: '6',
    name: "Un Lugar en Silencio 2",
    img: require("../assets/lugarsilencio.jpg"),
    price: 289,
    language: 'Ingles',
    horario: '1:30 PM, 3:45 PM',
    genero: 'Suspenso',
    duracion: '1h 55min',
    trailer: 'watch?v=41kMPKpZ_ps',
    star: 3,
    synopsis: 'El ex militar ciego que causó estragos en la primera entrega, volverá a verse envuelto en problemas. En aquella ocasión el hombre consiguió acabar de manera violenta con algunos de los jóvenes que tratan de entrar a robar a su hogar. Ahora, parece que un grupo de amigos ha entrado en su casa, pero con intenciones bien diferentes: van a tratar de tomarse venganza por sus malogrados colegas, en el asalto tiempo atrás.',
  }
]
